workspace:
  base: /go
  path: src/github.com/karantin2020/golang-docker

pipeline:
  publish:
    group: dopub
    image: plugins/docker
    repo: node3030/golang
    secrets: [ docker_username, docker_password ]
    tag: ['latest', '1.8.3']
    when:
      branch: master
      event: push
      
  release:
    group: dopub
    image: plugins/docker
    repo: node3030/golang
    secrets: [ docker_username, docker_password ]
    tags: ${DRONE_TAG##v}
    when:
      event: tag
